password-folder/password-service:
  url: "/password"
  policy: "password-folder/password-policy"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
