# Copyright (c) 2018 CA. All rights reserved.
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

version: '3.4'
services:
  gateway-dev:
    hostname: gateway-developer-example
    image: caapim/gateway:latest
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8000:8000"
    volumes:
      - /opt/SecureSpan/Gateway/node/default/etc/bootstrap/services/restman
      - ./common-services/build/gateway/bundle/common-services-1.0.0-full.install.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/common-services-1.0.0-full.install.bundle
      - ./business-integrations/build/gateway/bundle/business-integrations-1.0.0-full.install.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/business-integrations-1.0.0-full.install.bundle
      - ./consumer-solutions/build/gateway/bundle/consumer-solutions-1.0.0-full.install.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/consumer-solutions-1.0.0-full.install.bundle
      - ./global/build/gateway/bundle/global-1.0.0-full.install.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/global-1.0.0-full.install.bundle
      - ./routings/build/gateway/bundle/routings-1.0.0-full.install.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/routings-1.0.0-full.install.bundle
      - ./service-metrics/build/gateway/bundle/service-metrics-1.0.0-full.install.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/service-metrics-1.0.0-full.install.bundle
      - ./cassandra-example/build/gateway/bundle/cassandra-example-1.0.0-full.install.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/cassandra-example-1.0.0-full.install.bundle
      - ./clusterproperty-example/build/gateway/bundle/clusterproperty-example-1.0.0-full.install.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/clusterproperty-example-1.0.0-full.install.bundle
      - ./encass-annotations/build/gateway/bundle/encass-annotations-1.0.0-full.install.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/encass-annotations-1.0.0-full.install.bundle
      - ./idprovider-example/build/gateway/bundle/idprovider-example-1.0.0-full.install.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/idprovider-example-1.0.0-full.install.bundle
      - ./jms-example/build/gateway/bundle/jms-example-1.0.0-full.install.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/jms-example-1.0.0-full.install.bundle
      - ./mqnative-example/build/gateway/bundle/mqnative-example-1.0.0-full.install.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/mqnative-example-1.0.0-full.install.bundle
      - ./password-example/build/gateway/bundle/password-example-1.0.0-full.install.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/password-example-1.0.0-full.install.bundle
      - ./service-annotations/build/gateway/bundle/service-annotations-1.0.0-full.install.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/service-annotations-1.0.0-full.install.bundle
    secrets:
      - source: license
        target: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
      - source: privateKeys
        target: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/env/config/privateKeys
    environment:
      ACCEPT_LICENSE: "true"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "password"

      # Environment

      # A Private Key
      ENV.PRIVATE_KEY.test: |-
        algorithm: EC
        keyPassword: ''

      # Cluster Properties (Global Environment Properties)
      ENV.PROPERTY.gateway.log_levels: |-
        com.l7tech.server.policy.level = FINEST
        com.hazelcast.level = OFF
      ENV.PROPERTY.gateway.ENV.globalProperty: "cluster property from env var"

      # Context Variable Properties (Context Environment Properties)
      ENV.CONTEXT_VARIABLE_PROPERTY.environment-properties-example.contextVariableProperty: "context value from env var"

      # Service Properties (Service Environment Properties)
      ENV.SERVICE_PROPERTY.environment-properties-example.serviceProperty: "service property from env var"

      # 2 stored passwords
      ENV.PASSWORD.pets-db-password: "temp"
      ENV.PASSWORD.gateway: "7layer"

      # A JDBC Connection named 'pets-db' that uses the 'pets-db-password' created above
      ENV.JDBC_CONNECTION.pets-db: |-
        driverClass: "com.l7tech.jdbc.mysql.MySQLDriver"
        jdbcUrl: "TBD"
        properties:
          EnableCancelTimeout: "true"
        user: "admin"
        passwordRef: "pets-db-password"
        minimumPoolSize: 3
        maximumPoolSize: 15

      # A Cassandra Connection
      ENV.CASSANDRA_CONNECTION.Test: |-
        keyspace: Test
        contactPoint: Test
        port: 9045
        username: ''
        compression: NONE
        ssl: false

      # A certificate imported from a https URL
      ENV.CERTIFICATE.https://www.amazon.com: |-
        verifyHostname: false
        trustedForSsl: false
        trustedAsSamlAttestingEntity: false
        trustAnchor: false
        revocationCheckingEnabled: false
        trustedForSigningClientCerts: false
        trustedForSigningServerCerts: false
        trustedAsSamlIssuer: false

      # A PEM certificate with the data and its properties
      ENV.CERTIFICATE_FILE.www.google.com.pem: |-
        -----BEGIN CERTIFICATE-----
        MIIDxzCCAq+gAwIBAgIII8pR0+i7kWEwDQYJKoZIhvcNAQELBQAwVDELMAkGA1UE
        BhMCVVMxHjAcBgNVBAoTFUdvb2dsZSBUcnVzdCBTZXJ2aWNlczElMCMGA1UEAxMc
        R29vZ2xlIEludGVybmV0IEF1dGhvcml0eSBHMzAeFw0xODA4MjgxODIzMDBaFw0x
        ODExMjAxODIzMDBaMGgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlh
        MRYwFAYDVQQHDA1Nb3VudGFpbiBWaWV3MRMwEQYDVQQKDApHb29nbGUgTExDMRcw
        FQYDVQQDDA53d3cuZ29vZ2xlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
        BG69h/q0VI62C64qtA5497K+HJF6CcMSMDglj0ko5SpdM38ozhtLT4DdnNgbS5V9
        xfZ1A6EOf0N96VFSJG950aSjggFSMIIBTjATBgNVHSUEDDAKBggrBgEFBQcDATAO
        BgNVHQ8BAf8EBAMCB4AwGQYDVR0RBBIwEIIOd3d3Lmdvb2dsZS5jb20waAYIKwYB
        BQUHAQEEXDBaMC0GCCsGAQUFBzAChiFodHRwOi8vcGtpLmdvb2cvZ3NyMi9HVFNH
        SUFHMy5jcnQwKQYIKwYBBQUHMAGGHWh0dHA6Ly9vY3NwLnBraS5nb29nL0dUU0dJ
        QUczMB0GA1UdDgQWBBSh8zGNXn++GBb0M220OTqTpwIw0TAMBgNVHRMBAf8EAjAA
        MB8GA1UdIwQYMBaAFHfCuFCaZ3Z2sS3ChtCDoH6mfrpLMCEGA1UdIAQaMBgwDAYK
        KwYBBAHWeQIFAzAIBgZngQwBAgIwMQYDVR0fBCowKDAmoCSgIoYgaHR0cDovL2Ny
        bC5wa2kuZ29vZy9HVFNHSUFHMy5jcmwwDQYJKoZIhvcNAQELBQADggEBAIqwHvex
        +0f6LtZPaQhD+y/swPde4Lf05qsUH2gckipagPu5MivTFYM7vbtTYWBzjcdIH4vX
        UU/bw8IKdq0tAp6rWNlk008H1LBamTsOz/fzWTkel3VkKSmRk5OESbPcGAGszzjt
        yxhB2vS92C0hKlh7+RrjZtJ1QSmtLhGqhwO75GfQCzp/Yd0UEdWCqg53YcWqtx3+
        cZ612nBT8IkWeELQi9yEfO6RyR5Lki8ccsVQTsP19y9F35XFFNJbZsQs+OhmN5Kz
        n9oJbLJa81eS7Pr0HVdgSMLTSUARwBSG6uHL/RedS3m5dnIQUN4PpAaV6cejT+25
        7wBm1tvqBWx7JjE=
        -----END CERTIFICATE-----
      ENV.CERTIFICATE.www.google.com: |-
        verifyHostname: false
        trustedForSsl: false
        trustedAsSamlAttestingEntity: false
        trustAnchor: false
        revocationCheckingEnabled: false
        trustedForSigningClientCerts: false
        trustedForSigningServerCerts: false
        trustedAsSamlIssuer: false

      # A LDAP configuration
      ENV.IDENTITY_PROVIDER.LdapServer: |-
        type: BIND_ONLY_LDAP
        properties: {}
        identityProviderDetail:
          serverUrls:
          - ldaps://ldapserver:636
          useSslClientAuthentication: true
          bindPatternPrefix: ''
          bindPatternSuffix: ''

      # A Listen Port Configuration redirecting to a specific service
      ENV.LISTEN_PORT.DBServicePort: |-
        protocol: HTTPS
        port: 32323
        enabledFeatures:
        - Published service message input
        targetServiceReference: routings/db-service
        tlsSettings:
          clientAuthentication: NONE
          enabledVersions:
          - TLSv1
          - TLSv1.2
          - TLSv1.1
          enabledCipherSuites:
          - TLS_RSA_WITH_AES_256_CBC_SHA256
          - TLS_RSA_WITH_AES_256_GCM_SHA384
          - TLS_RSA_WITH_AES_256_CBC_SHA
          properties:
            usesTLS: true

      # A Listen port generating a FTP Service
      ENV.LISTEN_PORT.FTP: |-
        protocol: "FTP"
        port: 55555
        enabledFeatures:
          - "Published service message input"
        properties:
          portRangeCount: "100"
          portRangeStart: "55556"
          useExtendedFtpCommandSet: "false"

secrets:
  license:
    file: ./docker/license.xml
  # This is required to build the merged p12 file for the privatekeys
  privateKeys:
    file: ./lib/privateKeys