business-integrations/b2b-services:
  url: "/b2b/*"
  policy: "business-integrations/b2b-services"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
