createPet:
  policy: "common/entities/createPet"
  arguments:
  - name: "age"
    type: "string"
    requireExplicit: true
  - name: "name"
    type: "string"
    requireExplicit: true
  - name: "type"
    type: "string"
    requireExplicit: true
  results:
  - name: "pet-json"
    type: "string"
