mqnative-folder/mqnative-service:
  url: "/mqnative"
  policy: "mqnative-folder/mqnative-policy"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
