jdbc_con1:
  driverClass: "com.l7tech.jdbc.mysql.MySQLDriver"
  jdbcUrl: "jdbc:l7tech:mysql://localhost:3306"
  properties:
    EnableCancelTimeout: "true"
  user: "gateway"
  passwordRef: "jdbc_con_pass"
  minimumPoolSize: 3
  maximumPoolSize: 15
jdbc_con2:
  driverClass: "com.l7tech.jdbc.mysql.MySQLDriver"
  jdbcUrl: "jdbc:l7tech:mysql://localhost:3305"
  properties:
    EnableCancelTimeout: "true"
  user: "gateway"
  passwordRef: "jdbc_con_pass"
  minimumPoolSize: 3
  maximumPoolSize: 15
