clusterproperty-folder/clusterproperty-service:
  url: "/property"
  policy: "clusterproperty-folder/clusterproperty-policy"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
